# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1-stretch
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - setup_remote_docker
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: 
          name: "Build docker image and push to docker hub"
          command: 
              cp Dockerfile.Staging Dockerfile
              docker build -t anodiaroid/example-nodejs-circle
              docker push anodiaroid/example-nodejs-circle
      - run: echo Done
      # run tests!
      #- run: yarn test